name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t movie-booking-api:${{ github.sha }} .

    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-container movie-booking-api:${{ github.sha }}
        echo "Waiting for application to start..."
        sleep 15
        echo "Testing API endpoint..."
        for i in {1..5}; do
          if curl -f http://localhost:8080/api/movies; then
            echo "API is responding!"
            docker stop test-container
            docker rm test-container
            exit 0
          fi
          echo "Attempt $i failed, retrying..."
          sleep 3
        done
        echo "API failed to respond after 5 attempts"
        docker logs test-container
        docker stop test-container
        docker rm test-container
        exit 1

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: movie-booking-api
        path: target/movie-booking-api-*.jar
